### ISSUE TITLE
Помітив невелику помилку в тексті

### ISSUE THREAD

**Issue by karaaa006** [ivanzusko/javascript#11]
[Тестування](https://github.com/ivanzusko/javascript#%D1%82%D0%B5%D1%81%D1%82%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)

![image](https://user-images.githubusercontent.com/44326383/189837249-fec5b984-b876-49bb-b7ef-f89d3a4d453c.png)

**Comment by ivanzusko** [comment]
Вітаю @karaaa006 !

Перепрошую за доволі пізню відповідь...
Дякую, що звернули увагу!
